# RipCharts-Compatible LORAN Grid Configuration
# Exact reproduction of RipCharts grid parameters for multiple regions

# Global settings
grid_resolution: 0.027 # degrees (~3km spacing at mid-latitudes)
speed_of_light: 0.299792458 # km/μs

# LORAN Chains
chains:
  "9960":
    name: "Northeast US Chain"
    gri: 9960 # microseconds
    master:
      id: "M"
      name: "Seneca"
      latitude: 42.8367
      longitude: -76.8283
      emission_delay: 0.0
      coding_delay: 0.0
    secondaries:
      "W":
        id: "W"
        name: "Caribou"
        latitude: 46.8717
        longitude: -67.9933
        emission_delay: 13000.0 # μs
        coding_delay: 0.0
        asf: 0.0
      "X":
        id: "X"
        name: "Nantucket"
        latitude: 41.2650
        longitude: -69.9733
        emission_delay: 43000.0 # μs
        coding_delay: 0.0
        asf: 0.0
      "Y":
        id: "Y"
        name: "Carolina Beach"
        latitude: 34.0583
        longitude: -77.9050
        emission_delay: 43000.0 # μs
        coding_delay: 0.0
        asf: 0.0

  "7980":
    name: "Southeast US Chain"
    gri: 7980 # microseconds
    master:
      id: "M"
      name: "Malone"
      latitude: 30.9783
      longitude: -85.1550
      emission_delay: 0.0
      coding_delay: 0.0
    secondaries:
      "W":
        id: "W"
        name: "Grangeville"
        latitude: 30.4617
        longitude: -86.0683
        emission_delay: 11500.0 # μs
        coding_delay: 0.0
        asf: 0.0
      "X":
        id: "X"
        name: "Raymondville"
        latitude: 26.2500
        longitude: -97.7833
        emission_delay: 25500.0 # μs
        coding_delay: 0.0
        asf: 0.0
      "Y":
        id: "Y"
        name: "Baudette"
        latitude: 48.7283
        longitude: -94.6100
        emission_delay: 39500.0 # μs
        coding_delay: 0.0
        asf: 0.0
      "Z":
        id: "Z"
        name: "Boise City"
        latitude: 36.7283
        longitude: -102.5150
        emission_delay: 53500.0 # μs
        coding_delay: 0.0
        asf: 0.0

  "7980J":
    name: "Southeast US Chain (Jupiter Master)"
    gri: 7980 # microseconds
    master:
      id: "M"
      name: "Jupiter"
      latitude: 27.0467
      longitude: -80.1100
      emission_delay: 0.0
      coding_delay: 0.0
    secondaries:
      "S1_CB":
        id: "S1"
        name: "Carolina Beach"
        latitude: 34.0583
        longitude: -77.9050
        emission_delay: 11500.0 # μs
        coding_delay: 0.0
        asf: 0.0
      "S2_MAL":
        id: "S2"
        name: "Malone"
        latitude: 30.9783
        longitude: -85.1550
        emission_delay: 25500.0 # μs
        coding_delay: 0.0
        asf: 0.0

# Regional Configurations
regions:
  new_england_9960wy:
    name: "New England"
    display_name: "9960wy"
    description: "New England region with 9960 W-Y pairs"

    # Geographic bounds: [min_lon, min_lat, max_lon, max_lat]
    bounds: [-77.0, 36.0, -65.0, 42.0]

    # Station pairs to generate
    pairs:
      - chain_id: "9960"
        secondary_id: "W"
        family: "W"
        orientation: "vertical" # NW-SE lines
      - chain_id: "9960"
        secondary_id: "Y"
        family: "Y"
        orientation: "horizontal" # SW-NE lines

    # TD ranges to match RipCharts dense edge-to-edge coverage
    td_ranges:
      "9960_W":
        min_td: 11500.0 # Extended to match RipCharts leftmost lines
        max_td: 17000.0 # Extended to match RipCharts rightmost lines
        step: 50.0
        format: "{:05.0f}" # 5-digit format with trailing zeros
      "9960_Y":
        min_td: 42000.0 # Extended to match RipCharts southernmost lines
        max_td: 45000.0 # Extended to match RipCharts northernmost lines
        step: 50.0
        format: "{:05.0f}" # 5-digit format with trailing zeros

    # Calibration anchors to match RipCharts exactly
    calibration_anchors:
      - latitude: 41.6727 # 41° 40.36'N converted to decimal
        longitude: -69.9725 # -69° 58.35'W converted to decimal
        td_values:
          "9960_W": 13850.0 # RipCharts reference value - PRIMARY ANCHOR
          "9960_Y": 43950.0 # RipCharts reference value - PRIMARY ANCHOR

    # Label placement
    labels:
      enabled: true
      placement: ["start", "middle", "end"] # Where to place labels on lines
      min_line_length: 5.0 # km minimum line length for labeling
      format_trailing_zeros: true

  nc_va_ny_9960xy:
    name: "NC VA NY"
    display_name: "9960xy"
    description: "North Carolina, Virginia, New York region with 9960 X-Y pairs"

    bounds: [-78.0, 33.0, -70.0, 42.0]

    pairs:
      - chain_id: "9960"
        secondary_id: "X"
        family: "X"
        orientation: "vertical"
      - chain_id: "9960"
        secondary_id: "Y"
        family: "Y"
        orientation: "horizontal"

    td_ranges:
      "9960_X":
        min_td: 42500.0
        max_td: 44500.0
        step: 50.0
        format: "{:05.0f}"
      "9960_Y":
        min_td: 42800.0
        max_td: 44050.0
        step: 50.0
        format: "{:05.0f}"

    calibration_anchors:
      - latitude: 37.5
        longitude: -74.0
        td_values:
          "9960_X": 43500.0
          "9960_Y": 43400.0

    unwrapping:
      enabled: true
      gri: 9960.0
      smooth_iterations: 3

    labels:
      enabled: true
      placement: ["start", "middle", "end"]
      min_line_length: 5.0
      format_trailing_zeros: true

  fl_ga_sc_7980yz:
    name: "FL GA SC"
    display_name: "7980yz"
    description: "Florida, Georgia, South Carolina region with 7980J Y-Z pairs (Jupiter Master)"

    bounds: [-83.0, 27.0, -75.0, 35.0]

    pairs:
      - chain_id: "7980J"
        secondary_id: "S1_CB"
        family: "Y"
        orientation: "horizontal"
      - chain_id: "7980J"
        secondary_id: "S2_MAL"
        family: "Z"
        orientation: "vertical"

    td_ranges:
      "7980J_S1_CB":
        min_td: 11000.0
        max_td: 13000.0
        step: 50.0
        format: "{:05.0f}"
      "7980J_S2_MAL":
        min_td: 25000.0
        max_td: 27000.0
        step: 50.0
        format: "{:05.0f}"

    calibration_anchors:
      - latitude: 31.0
        longitude: -79.0
        td_values:
          "7980J_S1_CB": 12000.0
          "7980J_S2_MAL": 26000.0

    unwrapping:
      enabled: true
      gri: 7980.0
      smooth_iterations: 3

    labels:
      enabled: true
      placement: ["start", "middle", "end"]
      min_line_length: 5.0
      format_trailing_zeros: true

  south_fl_7980wz:
    name: "South FL"
    display_name: "7980wz"
    description: "South Florida region with 7980 W-Z pairs"

    bounds: [-83.0, 24.0, -75.0, 30.0]

    pairs:
      - chain_id: "7980"
        secondary_id: "W"
        family: "W"
        orientation: "vertical"
      - chain_id: "7980"
        secondary_id: "Z"
        family: "Z"
        orientation: "horizontal"

    td_ranges:
      "7980_W":
        min_td: 11000.0
        max_td: 13000.0
        step: 50.0
        format: "{:05.0f}"
      "7980_Z":
        min_td: 53000.0
        max_td: 55000.0
        step: 50.0
        format: "{:05.0f}"

    calibration_anchors:
      - latitude: 27.0
        longitude: -79.0
        td_values:
          "7980_W": 12000.0
          "7980_Z": 54000.0

    unwrapping:
      enabled: true
      gri: 7980.0
      smooth_iterations: 3

    labels:
      enabled: true
      placement: ["start", "middle", "end"]
      min_line_length: 5.0
      format_trailing_zeros: true

# Output settings
output:
  format: "geojson"
  coordinate_precision: 6 # decimal places
  include_labels: true
  include_metadata: true

  # GeoJSON properties for lines
  line_properties:
    - "family" # W, X, Y, Z
    - "kind" # "line"
    - "td" # TD value as number
    - "chain_id" # Chain identifier
    - "secondary_id" # Secondary identifier

  # GeoJSON properties for labels
  label_properties:
    - "family" # W, X, Y, Z
    - "kind" # "label"
    - "td" # TD value as number
    - "label" # Formatted label string
    - "chain_id" # Chain identifier
    - "secondary_id" # Secondary identifier
