# RipCharts-Compatible LORAN Grid Configuration
# Exact reproduction of RipCharts grid parameters for multiple regions

# Global settings
grid_resolution: 0.027 # degrees (~3km spacing at mid-latitudes)
speed_of_light: 0.299792458 # km/μs

# LORAN Chains
chains:
  "9960":
    name: "Northeast US Chain"
    gri: 9960 # microseconds
    master:
      id: "M"
      name: "Seneca"
      latitude: 42.8367
      longitude: -76.8283
      emission_delay: 0.0
      coding_delay: 0.0
    secondaries:
      "W":
        id: "W"
        name: "Caribou"
        latitude: 46.8717
        longitude: -67.9933
        emission_delay: 13000.0 # μs
        coding_delay: 0.0
        asf: 0.0
      "X":
        id: "X"
        name: "Nantucket"
        latitude: 41.2650
        longitude: -69.9733
        emission_delay: 27005.9 # μs - calibrated to RipCharts anchor points
        coding_delay: 0.0
        asf: 0.0
      "Y":
        id: "Y"
        name: "Carolina Beach"
        latitude: 34.0583
        longitude: -77.9050
        emission_delay: 42264.1 # μs - calibrated to RipCharts anchor points
        coding_delay: 0.0
        asf: 0.0

  "7980":
    name: "Southeast US Chain"
    gri: 7980 # microseconds
    master:
      id: "M"
      name: "Malone"
      latitude: 30.9783
      longitude: -85.1550
      emission_delay: 0.0
      coding_delay: 0.0
    secondaries:
      "W":
        id: "W"
        name: "Grangeville"
        latitude: 30.4617
        longitude: -86.0683
        emission_delay: 14075.4 # μs - calibrated to RipCharts primary anchor
        coding_delay: 0.0
        asf: 0.0
      "X":
        id: "X"
        name: "Raymondville"
        latitude: 26.2500
        longitude: -97.7833
        emission_delay: 25500.0 # μs
        coding_delay: 0.0
        asf: 0.0
      "Y":
        id: "Y"
        name: "Carolina Beach"
        latitude: 34.0628
        longitude: -77.9130
        emission_delay: 61537.7 # μs - calibrated to RipCharts with Malone master
        coding_delay: 0.0
        asf: 0.0
      "Z":
        id: "Z"
        name: "Cape Canaveral"
        latitude: 28.4667
        longitude: -80.5500
        emission_delay: 63586.8 # μs - calibrated to RipCharts primary anchor
        coding_delay: 0.0
        asf: 0.0

  "7980J":
    name: "Southeast US Chain (Jupiter Master)"
    gri: 7980 # microseconds
    master:
      id: "M"
      name: "Jupiter"
      latitude: 27.0467
      longitude: -80.1100
      emission_delay: 0.0
      coding_delay: 0.0
    secondaries:
      "S1_CB":
        id: "S1"
        name: "Carolina Beach"
        latitude: 34.0583
        longitude: -77.9050
        emission_delay: 46608.1 # μs - calibrated to RipCharts northern points
        coding_delay: 0.0
        asf: 0.0
      "S2_MAL":
        id: "S2"
        name: "Malone"
        latitude: 30.9783
        longitude: -85.1550
        emission_delay: 61021.0 # μs - calibrated to RipCharts northern points
        coding_delay: 0.0
        asf: 0.0

  "9980":
    name: "Southeast US Chain (9980)"
    gri: 9980 # microseconds
    master:
      id: "M"
      name: "Greenville"
      latitude: 34.8647
      longitude: -82.3700
      emission_delay: 0.0
      coding_delay: 0.0
    secondaries:
      "Y":
        id: "Y"
        name: "Carolina Beach"
        latitude: 34.0628
        longitude: -77.9130
        emission_delay: 61022.7 # μs - calibrated to anchor point
        coding_delay: 0.0
        asf: 0.0
      "Z":
        id: "Z"
        name: "Jupiter Inlet"
        latitude: 26.9489
        longitude: -80.0747
        emission_delay: 44661.3 # μs - calibrated to anchor point
        coding_delay: 0.0
        asf: 0.0

# Regional Configurations
regions:
  new_england_9960wy:
    name: "New England (9960 WY) — anchored to RipCharts"
    display_name: "9960wy"
    description: "New England region with 9960 W-Y pairs - anchored to RipCharts with offsets"

    # Geographic bounds: [min_lon, min_lat, max_lon, max_lat] - NE Canyons box
    bounds: [-77.0, 36.0, -65.0, 42.0]

    # Station pairs to generate
    pairs:
      - chain_id: "9960"
        secondary_id: "W"
        family: "W"
        orientation: "vertical" # NW-SE lines
      - chain_id: "9960"
        secondary_id: "Y"
        family: "Y"
        orientation: "horizontal" # SW-NE lines

    # TD ranges - expanded for edge-to-edge coverage
    td_ranges:
      "9960_W":
        min_td: 12000.0 # W: Extended west for full coverage
        max_td: 15500.0 # W: Extended east for full coverage
        step: 50.0
        format: "{:05.0f}" # 5-digit format with trailing zeros
      "9960_Y":
        min_td: 42000.0 # Y: Extended south for full coverage
        max_td: 44500.0 # Y: Extended north for full coverage
        step: 50.0
        format: "{:05.0f}" # 5-digit format with trailing zeros

    # Calibration anchors - four point calibration with offsets enabled
    calibration_anchors:
      - latitude: 40.700167 # Anchor A (mid-box)
        longitude: -70.559333
        td_values:
          "9960_W": 14250.0 # Target W=14250
          "9960_Y": 43800.0 # Target Y=43800
      - latitude: 38.931000 # Anchor B (south edge)
        longitude: -71.765000
        td_values:
          "9960_W": 14900.0 # Target W=14900
          "9960_Y": 42850.0 # Target Y=42850
      - latitude: 40.903000 # Anchor C (east edge)
        longitude: -65.123167
        td_values:
          "9960_W": 12800.0 # Target W=12800
          "9960_Y": 43450.0 # Target Y=43450
      - latitude: 41.6867 # Anchor D (Chatham elbow - CRITICAL)
        longitude: -69.9500
        td_values:
          "9960_W": 13850.0 # Target W=13850 (RipCharts exact)
          "9960_Y": 43950.0 # Target Y=43950 (RipCharts exact)

    # Label placement
    labels:
      enabled: true
      placement: ["start", "middle", "end"] # Where to place labels on lines
      min_line_length: 5.0 # km minimum line length for labeling
      format_trailing_zeros: true

  nc_va_ny_9960_xy:
    name: "NC VA NY"
    display_name: "9960xy"
    description: "North Carolina, Virginia, New York region with 9960 X-Y pairs"

    # Geographic bounds: [min_lon, min_lat, max_lon, max_lat] - updated per business partner feedback
    bounds: [-82.0, 30.0, -67.0, 41.0]

    # Station pairs to generate
    pairs:
      - chain_id: "9960"
        secondary_id: "X"
        family: "X"
        orientation: "vertical" # NW-SE lines
      - chain_id: "9960"
        secondary_id: "Y"
        family: "Y"
        orientation: "horizontal" # SW-NE lines

    # TD ranges - expanded for edge-to-edge coverage
    td_ranges:
      "9960_X":
        min_td: 24000.0 # X family - extended west for full coverage
        max_td: 29500.0 # X family - extended east for full coverage
        step: 50.0
        format: "{:05.0f}" # 5-digit format with trailing zeros
      "9960_Y":
        min_td: 35000.0 # Y family - extended south for full coverage
        max_td: 47000.0 # Y family - extended north for full coverage
        step: 50.0
        format: "{:05.0f}" # 5-digit format with trailing zeros

    # Calibration anchors to match RipCharts exactly
    calibration_anchors:
      - latitude: 33.30633 # Anchor A (bend/center-ish)
        longitude: -77.41517 # Anchor A (bend/center-ish)
        td_values:
          "9960_X": 27150.0 # RipCharts reference value - ANCHOR A
          "9960_Y": 39050.0 # RipCharts reference value - ANCHOR A
      - latitude: 35.93567 # Anchor B (NE corner)
        longitude: -72.86133 # Anchor B (NE corner)
        td_values:
          "9960_X": 26350.0 # RipCharts reference value - ANCHOR B
          "9960_Y": 41150.0 # RipCharts reference value - ANCHOR B

    # Label placement
    labels:
      enabled: true
      placement: ["start", "middle", "end"] # Where to place labels on lines
      min_line_length: 5.0 # km minimum line length for labeling
      format_trailing_zeros: true

  sc_ga_fl_7980_yz:
    name: "FL GA SC"
    display_name: "7980yz"
    description: "Florida, Georgia, South Carolina region with 7980 Y-Z pairs"

    # Geographic bounds: [min_lon, min_lat, max_lon, max_lat] - updated per business partner feedback
    bounds: [-82.0, 26.0, -73.0, 35.0]

    # Station pairs to generate
    pairs:
      - chain_id: "7980"
        secondary_id: "Y"
        family: "Y"
        orientation: "horizontal" # SW-NE lines
      - chain_id: "7980"
        secondary_id: "Z"
        family: "Z"
        orientation: "vertical" # NW-SE lines

    # TD ranges - expanded for edge-to-edge coverage
    td_ranges:
      "7980_Y":
        min_td: 57000.0 # Y family - extended south for full coverage
        max_td: 63500.0 # Y family - extended north for full coverage
        step: 50.0
        format: "{:05.0f}" # 5-digit format with trailing zeros
      "7980_Z":
        min_td: 42500.0 # Z family - extended west for full coverage
        max_td: 48000.0 # Z family - extended east for full coverage
        step: 50.0
        format: "{:05.0f}" # 5-digit format with trailing zeros

    # Calibration anchors to match RipCharts exactly
    calibration_anchors:
      - latitude: 32.61467 # Anchor A (Charleston offshore)
        longitude: -79.73250 # Anchor A (Charleston offshore)
        td_values:
          "7980_Y": 60500.0 # RipCharts reference value - ANCHOR A
          "7980_Z": 45450.0 # RipCharts reference value - ANCHOR A
      - latitude: 34.75700 # Anchor B (NE corner)
        longitude: -75.56317 # Anchor B (NE corner)
        td_values:
          "7980_Y": 59000.0 # RipCharts reference value - ANCHOR B
          "7980_Z": 45100.0 # RipCharts reference value - ANCHOR B

    # Label placement
    labels:
      enabled: true
      placement: ["start", "middle", "end"] # Where to place labels on lines
      min_line_length: 5.0 # km minimum line length for labeling
      format_trailing_zeros: true

  south_fl_7980_wz:
    name: "South FL"
    display_name: "7980wz"
    description: "South Florida region with 7980 W-Z pairs"

    # Geographic bounds: [min_lon, min_lat, max_lon, max_lat] - updated per business partner feedback
    bounds: [-83.0, 18.0, -74.0, 30.0]

    # Station pairs to generate
    pairs:
      - chain_id: "7980"
        secondary_id: "W"
        family: "W"
        orientation: "vertical" # NW-SE lines
      - chain_id: "7980"
        secondary_id: "Z"
        family: "Z"
        orientation: "horizontal" # SW-NE lines

    # TD ranges - expanded for edge-to-edge coverage
    td_ranges:
      "7980_W":
        min_td: 13000.0 # W family - extended west for full coverage
        max_td: 15500.0 # W family - extended east for full coverage
        step: 50.0
        format: "{:05.0f}" # 5-digit format with trailing zeros
      "7980_Z":
        min_td: 60000.0 # Z family - extended south for full coverage
        max_td: 64000.0 # Z family - extended north for full coverage
        step: 50.0
        format: "{:05.0f}" # 5-digit format with trailing zeros

    # Calibration anchors to match RipCharts exactly
    calibration_anchors:
      - latitude: 24.65683 # Anchor A (west of Bahamas)
        longitude: -79.03200 # Anchor A (west of Bahamas)
        td_values:
          "7980_W": 14150.0 # RipCharts reference value - ANCHOR A
          "7980_Z": 62000.0 # RipCharts reference value - ANCHOR A
      - latitude: 27.91967 # Anchor B (NE "point")
        longitude: -78.38850 # Anchor B (NE "point")
        td_values:
          "7980_W": 14500.0 # RipCharts reference value - ANCHOR B
          "7980_Z": 61350.0 # RipCharts reference value - ANCHOR B
      - latitude: 23.05633 # Anchor C (south edge, W of Matanzas)
        longitude: -81.72283 # Anchor C (south edge, W of Matanzas)
        td_values:
          "7980_W": 13800.0 # RipCharts reference value - ANCHOR C
          "7980_Z": 62650.0 # RipCharts reference value - ANCHOR C

    # Label placement
    labels:
      enabled: true
      placement: ["start", "middle", "end"] # Where to place labels on lines
      min_line_length: 5.0 # km minimum line length for labeling
      format_trailing_zeros: true

# Output settings
output:
  format: "geojson"
  coordinate_precision: 6 # decimal places
  include_labels: true
  include_metadata: true

  # GeoJSON properties for lines
  line_properties:
    - "family" # W, X, Y, Z
    - "kind" # "line"
    - "td" # TD value as number
    - "chain_id" # Chain identifier
    - "secondary_id" # Secondary identifier

  # GeoJSON properties for labels
  label_properties:
    - "family" # W, X, Y, Z
    - "kind" # "label"
    - "td" # TD value as number
    - "label" # Formatted label string
    - "chain_id" # Chain identifier
    - "secondary_id" # Secondary identifier
